#!/usr/bin/env zsh

# export DOTFILES="${HOME}/Workspace/dotfiles"

if [ -z "${DOTFILES}" ]; then
  echo "Modify install to point where your DOTFILES is installed"
  exit
fi
cd ${DOTFILES}

#check for antibody
antibody 2>/dev/null 1> /dev/null
if [ $? -ne 0 ]; then
    echo "Installing antibody"
    curl -sL https://git.io/antibody | bash -s
fi

function dirSymlinks {
  echo "Installing / Updating dirs"
  for d in */; do
    if [ ! -L ${HOME}/.${d%/} ] ; then
      echo "	${d%/} -> ${HOME}/.${d%/}"
      ln -sf "${DOTFILES}/${d%/}" "${HOME}/.${d%/}"
    fi
  done
}

function fileSymlinks {
  echo "Installing / Updating <dot> files"
  for f in *.rc; do
    if [ ! -L ${HOME}/.${f/.rc/} ] ; then
      echo "  ${f} -> ${HOME}/.${f/.rc/}"
      ln -sf "${DOTFILES}/${f}" "${HOME}/.${f/.rc/}"
    fi
  done
}


fileSymlinks
dirSymlinks
