#!/bin/bash

pdb_check=$(git grep -E -n 'set_trace')
if [ ${#pdb_check} -gt 0 ]
then
        echo "COMMIT REJECTED: commit contains code with break points. Please remove before commiting."
        echo $pdb_check
        exit 1
fi

#if [ -e .circleci/config.yml ]; then
#  cir=$(circleci config validate)
#  if [ ${#cir} -gt 45 ]; then
#    echo $cir
#    echo "COMMMIT REJECTED: CircleCI config is invalid - please fix it"
#    exit 1
#  fi
#fi
